### ISSUE TITLE
examples in chinese

### ISSUE THREAD

**Issue by Picatout** [breakintoprogram/agon-bbc-basic-adl#13]
What's up with examples?   They are not visible in code view. When downloaded they are not visible in geany editor and in Windows notepad shows Chinese characters!

**Comment by breakintoprogram** [comment]
Hi, the examples are in the tokenised BBC BASIC format so are not readable with a text editor. This folder is included as-is as a stipulation of the license with R.T.Russell. They will load in BBC BASIC fine though.
