### ISSUE TITLE
OPENOUT or OPENUP are not creating or writing to files

### ISSUE THREAD

**Issue by NicholasPratt** [breakintoprogram/agon-bbc-basic-adl#5]
Only tested so far on the emulator but can't get OPENOUT or OPENUP to create or write to files

**Comment by breakintoprogram** [comment]
This was caused by an optimisation in Z80 that relied upon the fact that LD HL, nn has a 2-byte operand, not 3 bytes.

**Comment by NicholasPratt** [comment]
That was quick :)
