### ISSUE TITLE
EXEC AUTOEXEC.TXT Doesn't allow run ./PROGRAM.BAS at startup

### ISSUE THREAD

**Issue by eightbitswide** [breakintoprogram/agon-bbc-basic-adl#7]
My AUTOEXEC.TXT is not working after replacing BBCBASIC.BIN with BBCBASIC24.BIN .

BASIC appears to load correctly and display it's message, but the "run . /AUTOEXEC.BAS' is no longer executed.
Is there a new way to do this in BBCBASIC24 or is this a bug?

Thanks!

**Comment by breakintoprogram** [comment]
This * may * be a bug. Does autoexec.bas run correctly if you load and run it from within BASIC?

**Comment by eightbitswide** [comment]
> This * may * be a bug. Does autoexec.bas run correctly if you load and run it from within BASIC?

Yes, if I LOAD "AUTOEXEC.BAS" after loading it loads and runs just fine.

**Comment by breakintoprogram** [comment]
Okay, that's probably a regression. It was working at one point. Should be an easy fix.

**Comment by breakintoprogram** [comment]
Bug was a regression caused by an over-enthusiastic RAM clear after the filename had been copied to the string accumulator.
