### ISSUE TITLE
OPENOUT does not return a handle for a new file

### ISSUE THREAD

**Issue by robogeek42** [breakintoprogram/agon-bbc-basic-adl#9]
OPENOUT returns a zero handle when a file does not exist. Expected a non-zero handle to be returned for a new file.

```
10 PRINT "Enter filename to write:"; : INPUT fn$
20 h%=OPENOUT(fn$)
30 PRINT "Handle ";h%
```

If the file exists, a non-zero handle is returned.

**Comment by breakintoprogram** [comment]
Hi @robogeek42 I think I fixed this in #5 that was released a day or so ago (version 1.02). Are you using version 1.01 of BBC BASIC for ADL? The code is working fine here with that version. Could you please confirm?

**Comment by robogeek42** [comment]
Should have upgraded before reporting. My apologies. I'll check it out,
and let you know. Thanks very much.

**Comment by breakintoprogram** [comment]
@robogeek42 No worries! I'll mark this one as not done then :-)
